name: Build Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsfml-dev \
            cmake \
            build-essential \
            debhelper \
            dh-make \
            fakeroot \
            wayland-protocols
          # Для GLFW Wayland support
          sudo apt-get install -y wayland-scanner

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)

      - name: Create DEB package
        run: |
          mkdir -p pkg/DEBIAN pkg/usr/games
          cp build/azteroids pkg/usr/games/

          cat > pkg/DEBIAN/control <<EOF
          Package: azteroids
          Version: 1.0-0
          Section: games
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Depends: libsfml-system2.5, libsfml-window2.5, libsfml-graphics2.5
          Description: Azteroids game
           A classic asteroids game built with SFML, EntityX, and GLFW.
          EOF
          dpkg-deb --build pkg azteroids_1.0-0_amd64.deb

      - name: Upload DEB artifact(gcc)
        uses: actions/upload-artifact@v4
        if: matrix.compiler == 'gcc'
        with:
          name: azteroids-deb-package-gcc
          path: azteroids_1.0-0_amd64.deb

      - name: Upload DEB artifact(clang)
        uses: actions/upload-artifact@v4
        if: matrix.compiler == 'clang'
        with:
          name: azteroids-deb-package-clang
          path: azteroids_1.0-0_amd64.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Download and install SFML
      shell: pwsh
      run: |
        $url = "https://github.com/SFML/SFML/releases/download/2.5.1/SFML-2.5.1-windows-vc15-64-bit.zip"
        $output = "$env:RUNNER_TEMP\SFML-2.5.1.zip"
        Write-Output "Downloading SFML from $url"
        Invoke-WebRequest -Uri $url -OutFile $output -UserAgent "GitHubActions"
        if (-not (Test-Path $output)) {
            throw "SFML download failed"
        }
        $sfmlPath = "C:\SFML-2.5.1"
        Expand-Archive -Path $output -DestinationPath $sfmlPath -Force
        Write-Output "SFML_DIR=$sfmlPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        Write-Output "CMAKE_PREFIX_PATH=$sfmlPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        Write-Output "PATH=$env:PATH;$sfmlPath\bin" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Build with CMake
      shell: pwsh
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ..
        cmake --build . --config Release --target azteroids

    - name: Create MSI package
      shell: pwsh
      run: |
        $productGuid = [guid]::NewGuid().ToString().ToUpper()
        $componentGuid = [guid]::NewGuid().ToString().ToUpper()
        @"
        <?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="Azteroids" Language="1033" Version="1.0.0.0" Manufacturer="YourCompany" UpgradeCode="$productGuid">
            <Package InstallerVersion="200" Compressed="yes" Comments="Windows Installer Package" Platform="x64"/>
            <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
            <MediaTemplate EmbedCab="yes"/>
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFiles64Folder">
                <Directory Id="INSTALLFOLDER" Name="Azteroids">
                  <Component Id="ApplicationFiles" Guid="$componentGuid" Win64="yes">
                    <File Id="AzteroidsEXE" Name="azteroids.exe" Source="build\Release\azteroids.exe" KeyPath="yes"/>
                  </Component>
                </Directory>
              </Directory>
            </Directory>
            <Feature Id="MainApplication" Title="Main Application" Level="1">
              <ComponentRef Id="ApplicationFiles"/>
            </Feature>
          </Product>
        </Wix>
        "@ | Out-File -FilePath product.wxs -Encoding utf8
        & "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe" -arch x64 -out product.wixobj product.wxs
        & "C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe" -out azteroids.msi product.wixobj

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: azteroids-msi-package
        path: azteroids.msi
